version: '3'

services:  
  postgres:
    image: postgres
    container_name: tinnova-challenge-db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./tinnova-challenge-back/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
